#!/bin/bash

## Reset tables configurations
#

echo "Reset tables configurations"

# Flush all rules
echo "	-- Flush iptable rules"
iptables -F
iptables -F -t nat
iptables -F -t mangle
iptables -F -t raw
# Erase all non-default chains
echo "	-- Erase all user defined chains"
iptables -X
iptables -X -t nat
iptables -X -t mangle
iptables -X -t raw


## Initialization
#

echo "Initialization"

# Change policy to DROP for INPUT and FORWARD
echo "	-- Set policies"
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT

# Allow established and related connection & tcp on port 4242
echo "	-- Keep established connection"
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Drop all invalid packets
echo "	-- Drop invalid packets"
iptables -A INPUT -m state --state INVALID -j DROP
iptables -A FORWARD -m state --state INVALID -j DROP
iptables -A OUTPUT -m state --state INVALID -j DROP


## DDOS Synflood
#

# Synflood protection
echo "DDOS Synflood protection"
iptables -N RATE-LIMIT
iptables -A RATE-LIMIT -p tcp --syn -m limit --limit 1/s --limit-burst 4 -j ACCEPT
iptables -A RATE-LIMIT -p tcp --syn -j DROP
echo "Port scan protection"
iptables -A FORWARD -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s -j ACCEPT

## Trafic configuration
#

echo "Trafic configuration"

# closes all ports except ssh, 80, 443
echo "	-- Opens  ports ssh (4242), https (443)"
iptables -A INPUT -p tcp -m tcp -m multiport --dports 4242,443 -j RATE-LIMIT
iptables -A INPUT -p tcp -m tcp --dport 80 -j DROP
iptables -A INPUT -p tcp --syn -m limit --limit 1/s --limit-burst 4 -j ACCEPT


## DDoS Pingflood
#

# Pingflood protection
echo "DDOS Pingflood protection"
/sbin/iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT

##  Make rule permanent
#

echo "Save iptables rules"
iptables-save > /etc/iptables/rules.v4
